wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715672256
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.11.5
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
test_size:
  desc: null
  value: 0.2
train_len:
  desc: null
  value: 900
test_len:
  desc: null
  value: 195
